// Grouped for writing, never shown to the visitor.
const FORTUNES = {
  reassurance: [
    "You don't need to have everything figured out today.",
    "You're probably doing better than your brain is currently reporting.",
    "Your life does not need to make sense all at once.",
    "It's okay that this is hard. It is hard.",
    "You are allowed to be a work in progress and a whole person at the same time.",
    "Nothing about you needs fixing before you're allowed to rest.",
    "A bad day is not a verdict on your whole life.",
    "You've gotten through every one of your worst days so far. That's not nothing.",
    "It's fine to be a little bit behind. Most people are.",
    "You can be tired and still be doing a good job.",
    "The version of you that's struggling is still worth being kind to.",
    "You don't have to earn a nice moment.",
    "Some days the win is just getting to the end of it.",
    "Feeling lost usually just means you're somewhere new.",
    "You are not too much. You are just enough of a lot of things.",
  ],
  encouragement: [
    "Try the small version first.",
    "You can start before you feel ready. Almost everyone does.",
    "The first draft is supposed to be bad. That's its whole job.",
    "Do the next tiny thing. Then maybe another one.",
    "Half-done is more done than not started.",
    "You've done hard things before, usually while complaining. That still counts.",
    "It's not too late to try the thing.",
    "You can be scared and do it anyway. Or be scared and not do it today. Both are allowed.",
    "Small progress still moves you.",
    "The thing you're putting off is probably smaller than it looks from here.",
    "You don't need permission. But if you want it: go ahead.",
    "Being a beginner is a perfectly respectable thing to be.",
    "Ten minutes is a real amount of time.",
    "Somewhere there's a future you who is glad you kept going.",
  ],
  perspective: [
    "In a year, you'll remember very little of what's worrying you this afternoon.",
    "What people notice about you is mostly kinder than what you notice about yourself.",
    "Nobody is thinking about that awkward thing you said nearly as much as you are.",
    "The sky has been doing this for a very long time. It's fine to just look at it for a bit.",
    "A lot of the good things in your life started out looking like nothing.",
    "Very few decisions are as permanent as they feel at night.",
    "Everyone you admire has a drawer full of things that didn't work.",
    "You're allowed to want a quieter life than the one you were told to want.",
    "Not every feeling needs a plan.",
    "Somewhere right now, someone is learning to ride a bike. It's going fine.",
    "The past was also confusing back when it was the present.",
    "A lot of \"too late\" is really just \"later than I expected.\"",
    "Your life is not a race. Nobody is even holding a stopwatch.",
    "Whatever matters will still matter after you've had a glass of water.",
  ],
  funny: [
    "Somewhere in your future is a really good lunch.",
    "Have something delicious today. This is an official recommendation.",
    "You are more than the sum of your unread emails.",
    "A pigeon somewhere is having a worse day than you, and it's still out there trying.",
    "Your houseplants believe in you. Well, most of them.",
    "Help! I'm being held prisoner in a fortune cookie factory. Just kidding. Have a nice day.",
    "This fortune has been reviewed and approved by a committee of one cat.",
    "You will soon encounter a snack. Proceed with confidence.",
    "Statistically, you are due for a good sandwich.",
    "Reminder: you are a mammal. Mammals need naps.",
    "Your browser has too many tabs open. So does your brain. Both are forgiven.",
    "Somewhere a dog would be very excited to meet you, specifically.",
    "It is never the wrong time for a little treat.",
    "You have exactly the right number of socks. (You don't. But it's fine.)",
    "Today's forecast: mostly you, with a chance of snacks.",
    "You cracked a cookie open. Look at you, getting things done.",
  ],
  gentleReminders: [
    "Drink some water. Then you can go back to whatever this is.",
    "Unclench your jaw. Drop your shoulders. There you go.",
    "You can put your phone down for a minute. It will wait.",
    "When did you last eat something? Be honest.",
    "Open a window if you can. Air is good.",
    "You are allowed to change your mind.",
    "It's okay to say no to things, even nice things.",
    "Go outside for five minutes. That's the whole assignment.",
    "You don't have to reply to that right now.",
    "Stretch your arms up. Higher. Okay, good.",
    "The dishes can wait until tomorrow. They're not going anywhere.",
    "Be as patient with yourself as you'd be with a friend.",
    "Look up from the screen at something far away for a second.",
    "It's okay to ask for help. People like being asked more than you'd think.",
  ],
  friendship: [
    "Someone is glad you exist and probably hasn't said it lately.",
    "Text the friend you've been meaning to text. Just \"hey\" is enough.",
    "You've been a good part of someone's day without knowing it.",
    "The people who love you are not keeping score.",
    "Someone still laughs about something you said once.",
    "You are somebody's favorite person to tell things to.",
    "Friendships can survive long silences. Yours probably have.",
    "You don't have to be interesting to be good company.",
    "Someone remembers a kindness of yours that you've completely forgotten.",
    "Showing up is most of friendship. Snacks are the rest.",
    "Somebody saw something recently and thought, \"they'd like this.\" They meant you.",
    "The right people won't need you to perform.",
    "You're allowed to be the one who reaches out first. It's a nice thing to be.",
  ],
  uncertainty: [
    "Not knowing what happens next is uncomfortable. It also means it isn't decided yet.",
    "You don't have to know where you're going to take one more step.",
    "\"I'm not sure yet\" is a complete answer.",
    "You can make a good decision without making the perfect one.",
    "Some questions need more time, not more thinking.",
    "You're allowed to wait and see.",
    "Plans are just guesses with nice handwriting.",
    "Nobody has a map. Some people are just better at pretending.",
    "It's okay not to know what you want yet.",
    "You don't need to see the whole staircase. Just the next step.",
    "Maybe is a perfectly good place to stay for a while.",
    "You can hold two feelings at once. Most people are holding about six.",
    "Most people are making it up as they go. You're in good company.",
  ],
  change: [
    "You're allowed to become someone slightly different.",
    "Outgrowing something doesn't mean it wasn't good.",
    "You can miss something without needing it back.",
    "It's okay to grieve a version of your life that didn't happen.",
    "New things feel strange before they feel like yours.",
    "You don't have to like a change to get through it.",
    "Some doors close quietly. That's allowed too.",
    "You've already changed so many times. You're good at this, actually.",
    "The old you did their best. Let them rest.",
    "It's okay if the new normal takes a while to feel normal.",
    "Sometimes leaving is the brave part.",
    "Seasons change without asking anyone. You can too.",
    "You don't have to be who you were last year.",
  ],
  rest: [
    "You don't have to turn today into anything important.",
    "Rest is not a reward. You can just have it.",
    "It's okay to do nothing for a while. Nothing is a real activity.",
    "How much you got done today is not how much you're worth.",
    "Lie down for a bit. The ceiling has been waiting to see you.",
    "You're allowed to cancel plans and stay in and be a potato.",
    "A slow day is still a day.",
    "Tired is information, not a character flaw.",
    "You can go to bed early. No one's checking.",
    "Let today be a soft one.",
    "Being still is not the same as being stuck.",
    "Sometimes the most productive thing is a nap.",
    "You've been carrying a lot. You can set some of it down.",
    "Comfy clothes are a valid life choice.",
  ],
  loneliness: [
    "Feeling lonely means you have love to give. That's not a small thing.",
    "Someone else is up right now feeling a lot like this. You're less alone than it seems.",
    "You are good company, even to yourself.",
    "Being alone tonight doesn't mean being alone forever.",
    "A lot of your people are just people you haven't met yet.",
    "Wanting more connection is one of the most human things there is.",
    "Almost everyone feels on the outside sometimes. Even the ones who look like they don't.",
    "Talk to the barista. Pet the dog. Small hellos count.",
    "Somewhere, someone would be really glad to hear from you.",
    "You are worth getting to know.",
    "A quiet room isn't empty if you're in it.",
    "Loneliness is a feeling, not a fact about you.",
    "This little cookie was thinking of you. It's not much, but it's sincere.",
  ],
  confidence: [
    "You know more than you think you do.",
    "You're allowed to take up space.",
    "Your weird is somebody's favorite thing about you.",
    "You don't need to shrink to be likable.",
    "Your opinion counts, even when it's quiet.",
    "You've gotten better at things without even noticing.",
    "You don't have to be the best at it. You just have to be you at it.",
    "Say the thing. Your voice belongs in the room.",
    "You've been underestimating yourself. Mostly by yourself.",
    "You're allowed to be proud of small things.",
    "Your taste is good. Trust it a little more.",
    "Someone who knows you well would argue with the mean thing you just thought about yourself.",
    "You're not an impostor. You're just new.",
  ],
  littleJoys: [
    "There are still songs you haven't heard that you'll love.",
    "Somewhere a cat is sitting in a sunbeam, and that is the correct way to live.",
    "Warm socks fresh out of the dryer. That's the fortune.",
    "There are still books out there that will feel like they were written for you.",
    "The smell of rain on a sidewalk is free and available to you.",
    "A good cup of tea fixes nothing and helps with almost everything.",
    "You have not yet eaten every good pastry. There's still time.",
    "Toast. Toast is good.",
    "At some point you'll laugh so hard you can't breathe, probably at something stupid.",
    "There's a sunset tonight whether you watch it or not. You might.",
    "The first sip of something cold on a hot day. Remember that one.",
    "Clean sheets are in your future. Hang in there.",
    "Someone, somewhere, is baking bread right now. The world is like that sometimes.",
    "Look for one nice thing today. It doesn't have to be big. A good leaf is fine.",
    "Fresh-cut grass, old photos, the first bite of a peach. Little things are still things.",
    "There is a really good nap somewhere in your near future.",
  ],
};

// Quiet surprises for certain hours. Never announced.
const TIMELY = {
  lateNight: [
    "Whatever you're trying to solve can probably wait until morning.",
    "Everything looks bigger at night. It shrinks back down by breakfast.",
    "Night thoughts are not always true thoughts.",
    "The internet will still be here tomorrow. Go to sleep, if you can.",
    "If you're awake right now, be extra gentle with yourself. It's late.",
  ],
  morning: [
    "You haven't messed today up yet. Give it a chance.",
    "Today hasn't decided what kind of day it is yet.",
    "Start slow. The day can come to you.",
    "Breakfast counts as taking care of yourself.",
  ],
  sundayEvening: [
    "Tomorrow does not need to be solved tonight.",
    "The week can start without you worrying about it in advance.",
    "Let Sunday be Sunday for a few more hours.",
  ],
};

// Shown once, after a handful of cookies.
const ENOUGH = "That's a lot of cookies. The rest will still be here later, you know.";
